import './globals.css'
import { Inter } from 'next/font/google'
import "./tailwind-global.css"
import StyledComponentsRegistry from './lib/registry'
import { Roboto } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  weight:['400','700'],
  style:['italic', 'normal'],
  subsets:['latin'],
  variable: "--font-roboto",
  display:"optional"
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      <head lang="es" className={roboto.className}/>
      <body className={inter.className}>
        <StyledComponentsRegistry>
           {children}
        </StyledComponentsRegistry>
        </body>
    </html>
  )
}
